<!doctype html>
<html lang="en">
   <head>
      <style>

table, td, tr {
    padding:0 !important;
margin:0 !important;
}

body {
   font-family: sans-serif;
}

.headrow {
    background-color:#0b5394;
    padding:0 !important;
    color:#ffffff;
    text-align:center;
    font-weight:400;
}

.normrow {
    padding:0px;
    text-align:center;
}

.normrowb {
    padding:0px;
    text-align:center;
    border:1px solid #d9d9d9;
}

.normcell {
    border:1px solid #d9d9d9;
    padding:0px;
}

.normcellb {
    border:0;
    padding:0px;
}
    
.grncell {
    background-color:#2ea442;
    border:1px solid #d9d9d9;
    padding:0px;
}
   
.oracell {
    background-color:#ff9900;
    border:1px solid #d9d9d9;
    padding:10px;
}
   
.subhtxt {
    font-size:14px;
line-height:16px;
    text-align:center;
    margin-bottom:10px;
}

.subhtxtb {
    font-size:14px;
line-height:16px;
    text-align:center;
    margin-bottom:0;
}

.subhtxtw {
    font-size:14px;
line-height:16px;
    text-align:center;
    margin-bottom:0;
    color:#ffffff;
    margin-top:0;
}

.normtxt {
    font-size:11px;
line-height:13px;
    text-align:center;
}

.normtxtw {
    font-size:11px;
line-height:13px;
    text-align:center;
    color:#ffffff;
}

.legaltxt1 {
    font-size:8px;
line-height:9px;
    text-align:center;
}

.legaltxt2 {
    font-size:6px;
line-height:7px;
    text-align:center;
}

.legaltxt3 {
    font-size:7px;
line-height:8px;
    color:#ff0000;
}

.legaltxt4 {
    font-size:7px;
line-height:8px;
    color:#000000;
    font-style: italic;
}

td {
padding: 5px 10px !important;
}

tr {
    padding:5px 10px !important;
}

/*new Style*/
.head1 {
    background-color:#d9d9d9;
    padding:10px 30px;
}

.head1txt {
    font-size:30px;
    color:#0b5394;
    margin:0;
    line-height:30px;
}

.generaltxt {
    font-size:12px;
    line-height:12px;
}

.generaltxtw {
    font-size:11px;
    color:#ffffff;
    line-height:12px;
}

.generaldiv {
    padding:0 20px;
    border:1px solid #d9d9d9;
}

.head2 {
    background-color:#0b5394;
    padding:5px 30px;
}

.head2txt {
    font-size:13px;
    color:#ffffff;
    margin:0;
}

.generaltxtg {
    font-size:11px;
    color:#2ea442;
    text-align:center;
    line-height:12px;
}

.generaltxtr {
    font-size:11px;
    color:#ff0000;
    text-align:center;
    line-height:12px;
}

.generaltxtbig {
    font-size:14px;
    color:#000000;
    line-height:15px;
}

.generaltxtbigb {
    font-size:14px;
    color:#000000;
    line-height:15px;
    margin:0;
}

.slipbodtxt {
    font-size:13px;
    color:#000000;
    line-height:16px;
}
</style>
</head>

<body>

<table width="100%" style="background-color:#d9d9d9;">
<tr>
<td>
<p class="head1txt"><img src="assets/images/logostaff.png" style="max-height:25px; margin:10px; !important"></p>
</td>
</tr>
</table>


<div class="generaldiv">
<p class="generaltxt">StaffLife (<strong>SL</strong>) is a world-first, <strong>Employee Ethics</strong> & <strong>Performance Bureau</strong>.<br/>
SL is designed to enhance and protect both Employers & Employees. 
</p>
</div>

<div class="head2">
<p class="head2txt">My StaffLife Profile</p>
</div>

<div class="generaldiv">
<p class="generaltxt">Imagine trying to obtain a loan from a bank by providing your own document stating that you are creditworthy. Sounds absurd, right? Well that is generally how recruitment works - which is why most Employers are sceptical about CVs’ accuracy.</strong> 
<br/><br/>
Your SL Profile is a powerful, independant, comprehensive, verifiable historical record of your employment, with data generated by approved Employers (Members). Our primary focus is data accuracy and integrity - which assists Members to make an informed decision. Your Profile may only be viewed or edited by a Member with <strong>your signed consent.</strong>
<br/><br/>
<strong>We store two types of data:</strong>
<br/><br/>
<strong>Ethics & Basics:</strong> verifiable data such as employment dates & contract details, attendance, resignation & notice period, etc. This data is removed if found to be inaccurate (when challenged by you).
<br/><br/>
<strong>Performance:</strong> punctuality, dedication, skills, work quality, productivity, etc. SL makes it clear that this is the Member’s opinion, and it is up to future Employers to analyse the data. To reduce subjective information, only tick boxes are used (no free text). We provide vital statistics about this Member to other Members, such as the ratio of negative/positive data submitted, benchmarking, deviations and other parameters to deter misleading or malicious data.</p>
</div>

<div class="head2">
<p class="head2txt">How it works</p>
</div>

<div class="generaldiv">
<p class="generaltxt">The Member updates your Profile periodically (and up to 30 days after termination). You may log in at any time to view your Profile. You will have access to most of the data, including a list of Employers that you have given consent to. You have the right to challenge information in the Ethics & Basics section.
<br/><br/>
Employers are vetted by SL to ensure they are a registered company and are checked against our own/3rd party databases for clearances. Your privacy and profile accuracy is of paramount importance to us.
</p>
</div>

<div class="head2">
<p class="head2txt">Should I Sign This Form?</p>
</div>

<div class="generaldiv">
<p class="generaltxt">Evaluate which Employee group (below) applies to you the most. <strong>Most individuals are well aware of their value and conduct.</strong></p>
</div>



<div>
    <table>
        <tr>
            <td  class="normcell" style="background-color:#2ea442; padding:5px; margin:0;" width="50%">
                <p class="head2txt" style="text-align:center; margin-top:5px;"><img src="assets/images/tick.png" style="max-height:13px;">&nbsp;Assets</p>
                <p class="generaltxtw">You have a good, positive attitude and strong work ethic. You are productive, dedicated and strive to act in the best interests of the business. You learn and improve with time and do not lie about your abilities and skills. Most Employees enjoy working with you.
<br/><br/>
<strong>I'm not perfect</strong><br/>
Neither is anyone else - mistakes happen. What matters is your contribution and how you are viewed as a whole. Most Employers accept that not all records are always positive.
<br/><br/>
<strong>Benefits of signing this form</strong><br/>
A verifiable, trustworthy StaffLife Profile distinguishes you from others, resulting in better opportunities and higher earnings.</p>
        </td>
            <td  class="normcell" style="background-color:#ff9900; padding:5px; margin:0;" width="50%">
                <p class="head2txt" style="text-align:center; margin-top:5px;"><img src="assets/images/cross.png"  style="max-height:13px;">&nbsp;Liabilities</p>
                <p class="generaltxtw">You generally have a poor attitude and may be disruptive, negligent, malicious or toxic within your work environment. You are dishonest about your employment history, skills, qualification or abilities. You have little or no regard for your work ethic or the goals of the business.
<br/><br/>
<strong>You can commit to change</strong><br/>
Evaluate carefully whether you are willing to improve. SL helps by giving you a new sense of accountability for your actions. Very few people who truly want to change, cannot do so. 
<br/><br/>
<strong>Consequences of signing this form</strong><br/>
If you do not commit to changing yourself, you may earn less and find it harder to be hired by a SL Member.
</p>
            </td>
        </tr>
        <tr>
            <td  class="normcell" style="background-color:#d9d9d9; padding:5px; margin:0;" width="50%">
                <p class="generaltxtg"><strong>If you are generally within this group, we 
advise you proceed and begin reaping your rewards!</strong></p>
        </td>
            <td  class="normcell" style="background-color:#d9d9d9; padding:5px; margin:0;" width="50%">
                <p class="generaltxtr"><strong>If you are generally within this group, we 
strongly advise against signing this form!</strong></p>
        </td>
    </tr>
</table>

</div>

<div class="generaldiv">
    <p class="generaltxt"><span style="color:#0b5394;">Somewhere in the middle?</span> You will likely show both positive and negative data equally. Strive to improve. 
<br/><br/>
<span style="color:#0b5394;">Unsure?</span> Ask yourself, what would most of my past Employers, fellow students, etc. objectively say about me? If it's closer to the “Assets” than the “Liabilities” group, your benefits are generally higher than your exposure.</p>
</div>
<div>
    <p style="font-size:9px; text-align:center; margin-top:25px;">
This page is for the candidate/Employee to keep. Further information can be found on www.<span style="color:#2ea442;">Staff</span><span style="color:#ff9900;">Life</span>.com<br/></p>

<hr>
<p style="font-size:9px; text-align:center;"><span style="color:#ff0000;">Copyright &copy; StaffLife.</span> <strong>D1004.</strong> Reproduction & editing is strictly prohibited.</p>
</div>

<table width="100%">
            <tr class="head2" style="border:0 !important;">
                <td colspan="1" width="25%">
                    <p style="text-align:center;" style="margin:0px !important;"><img src="assets/images/logostaff.png" style="max-height:30px;"></p>
                </td>
                <td colspan="2" width="50%">
                    <p class="head2txt" style="text-align:center; margin:0px !important;">STAFFLIFE INDEMNIFICATION AND PERMISSION &nbsp;(SLIP)</p>
                </td>
                <td colspan="1" width="25%">
                    <p class="subhtxtw" style="margin:0px !important;"><?php echo $employeeData->uniquenumber; ?></p>
                </td>
            </tr>
</table>

<div class="generaldiv">
<table width="100%">
    <tr>
        <td width="50%">
            <p class="generaltxtbigb">StaffLife (SL)</p>
        </td>
        <td width="50%">
            <p class="generaltxtbigb" style="text-align:right;">{{ $employeeWatchRow->created_at }}</p>
        </td>
    <tr>
</table>
<p class="generaltxtbig" style="text-align:center;">{{ $user->companyname }}&nbsp;(Employer/Member)</p>
<p class="generaltxtbig" style="text-align:center;">{{ $employeeData->first_name ." "}}{{ $employeeData->last_name }}&nbsp;&nbsp;(Candidate/Employee)</p>
</div>
<div class="generaldiv">
<p class="slipbodtxt">I, <strong>{{ $employeeData->first_name ." "}}{{ $employeeData->last_name }}</strong>, identification number ({{ $employeeData->idnumber }}) understand that <strong>{{ $user->companyname }}</strong> is a StaffLife Member in good standing. Although consent may not be required in my country/region, I do agree to my employment Profile being accessed and/or edited by {{ $user->companyname }}.</p>
</div>
<div class="head2">
<p class="head2txt">My StaffLife Profile (employment history)</p>
</div>

<div class="generaldiv">
<p class="slipbodtxt">The goal of StaffLife is to improve your ability to find work, get better opportunities and increase earnings and benefits. It is also important to consider that your StaffLife Profile may hamper your career if your conduct, ethics or performance are poor. Most individuals who apply themselves, benefit tremendously with their historical records available to potential Employers. StaffLife has implemented multiple measures to ensure your data is fair and accurate. Your StaffLife Profile is associated with your personal email: {{ $employeeData->email }}.</p>
</div>

<div class="head2">
<p class="head2txt">Consent & Data Accuracy / Fairness</p>
</div>

<div class="generaldiv">
<p class="slipbodtxt">A StaffLife Member may access or update your Profile with your consent only (by signing this form) except for pre-employment data. You will receive a notification (on your personal email) when your Profile is accessed or edited. You may log in to your profile (at any time) and challenge data pertaining to Ethics & Basics (within 30 days).  Evidence may be required from either party to validate the information in question. You are entitled to an unlimited number of challenges, provided they are successful. If a Member successfully proves information you have challenged two times in one year, you will have no further challenges available that year. You may request/remind your Employer to submit your Performance data, however, it is optional for Members to do so. Records may remain for up to 10 years, although rehabilitation processes are available to clear your negative data (process system is at the discretion of SL).</p>
</div>

<div class="head2">
<p class="head2txt">My Declaration</p>
</div>

<div class="generaldiv">
<p class="slipbodtxt">I agree to work ethically and to the best of my ability whilst working for a StaffLife Member. I will not abuse employment laws for my unjust benefit and declare that I have not habitually referred past Employers to the legal system on an unfounded basis. I have disclosed all relevant information to {{ $user->companyname }} and the information I have submitted in my application is accurate to the best of my knowledge.
<br/><br/>
I will not hold StaffLife liable for any consequences resulting from its advice or my Profile in general. 
</p>
</div>

<div style="height:20px;"></div>
<table width="100%">        
        <tr class="normrow">
            <td colspan="2" rowspan="3" class="normcell" width="50%">
                <p class="normtxt">
            I understand and agree to the contents of this form and the potential benefits & exposure:
</p>
            </td>
        
            <td colspan="1" rowspan="1" style="border-bottom:1px solid #000000;" width="25%">&nbsp;<br/>&nbsp;</td>
            <td colspan="1" rowspan="1" style="border-bottom:1px solid #000000;" width="25%">&nbsp;<br/>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="1" rowspan="1"><p class="normtxt">Signature</p></td>
            <td colspan="2" rowspan="1"><p class="normtxt">Today&rsquo;s Date</p></td>
        </tr>
        <tr>
            <td colspan="2" rowspan="1"><p class="normtxt">{{ $employeeData->first_name ." "}}{{ $employeeData->last_name }} - (ID {{ $employeeData->idnumber }})</p></td>
        </tr>
       

</table>

<div>
<div style="height:30px;"></div>
<hr/>
    <p style="font-size:9px; text-align:center;"><span style="color:#ff0000;">Copyright &copy; StaffLife.</span> <strong>D1005</strong> Reproduction & editing is strictly prohibited.</p>
</div>


    </body>
</html>